// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: MonitoringService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MonitoringService_GetCpuUsageInfo_FullMethodName    = "/proto.MonitoringService/GetCpuUsageInfo"
	MonitoringService_StreamCpuUsageInfo_FullMethodName = "/proto.MonitoringService/StreamCpuUsageInfo"
)

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitoringServiceClient interface {
	// Get the CPU usage information
	GetCpuUsageInfo(ctx context.Context, in *CpuUsageInfoRequest, opts ...grpc.CallOption) (*CpuUsageInfoResponse, error)
	// Stream the CPU usage information
	StreamCpuUsageInfo(ctx context.Context, in *CpuUsageInfoRequest, opts ...grpc.CallOption) (MonitoringService_StreamCpuUsageInfoClient, error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) GetCpuUsageInfo(ctx context.Context, in *CpuUsageInfoRequest, opts ...grpc.CallOption) (*CpuUsageInfoResponse, error) {
	out := new(CpuUsageInfoResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetCpuUsageInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) StreamCpuUsageInfo(ctx context.Context, in *CpuUsageInfoRequest, opts ...grpc.CallOption) (MonitoringService_StreamCpuUsageInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[0], MonitoringService_StreamCpuUsageInfo_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &monitoringServiceStreamCpuUsageInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MonitoringService_StreamCpuUsageInfoClient interface {
	Recv() (*CpuUsageInfoResponse, error)
	grpc.ClientStream
}

type monitoringServiceStreamCpuUsageInfoClient struct {
	grpc.ClientStream
}

func (x *monitoringServiceStreamCpuUsageInfoClient) Recv() (*CpuUsageInfoResponse, error) {
	m := new(CpuUsageInfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitoringServiceServer is the server API for MonitoringService service.
// All implementations must embed UnimplementedMonitoringServiceServer
// for forward compatibility
type MonitoringServiceServer interface {
	// Get the CPU usage information
	GetCpuUsageInfo(context.Context, *CpuUsageInfoRequest) (*CpuUsageInfoResponse, error)
	// Stream the CPU usage information
	StreamCpuUsageInfo(*CpuUsageInfoRequest, MonitoringService_StreamCpuUsageInfoServer) error
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMonitoringServiceServer struct {
}

func (UnimplementedMonitoringServiceServer) GetCpuUsageInfo(context.Context, *CpuUsageInfoRequest) (*CpuUsageInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCpuUsageInfo not implemented")
}
func (UnimplementedMonitoringServiceServer) StreamCpuUsageInfo(*CpuUsageInfoRequest, MonitoringService_StreamCpuUsageInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCpuUsageInfo not implemented")
}
func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}

// UnsafeMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServiceServer will
// result in compilation errors.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

func _MonitoringService_GetCpuUsageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CpuUsageInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetCpuUsageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetCpuUsageInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetCpuUsageInfo(ctx, req.(*CpuUsageInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_StreamCpuUsageInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CpuUsageInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitoringServiceServer).StreamCpuUsageInfo(m, &monitoringServiceStreamCpuUsageInfoServer{stream})
}

type MonitoringService_StreamCpuUsageInfoServer interface {
	Send(*CpuUsageInfoResponse) error
	grpc.ServerStream
}

type monitoringServiceStreamCpuUsageInfoServer struct {
	grpc.ServerStream
}

func (x *monitoringServiceStreamCpuUsageInfoServer) Send(m *CpuUsageInfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

// MonitoringService_ServiceDesc is the grpc.ServiceDesc for MonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCpuUsageInfo",
			Handler:    _MonitoringService_GetCpuUsageInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCpuUsageInfo",
			Handler:       _MonitoringService_StreamCpuUsageInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "MonitoringService.proto",
}
